### ISSUE TITLE
go install `github.com/pandatix/go-abnf/cmd/pap@latest` not working

### ISSUE THREAD

**Issue by Timothepou** [pandatix/go-abnf#20]
As the title states, when installing pap (using go 1.22.1), this error appears :

```bash
$ go install github.com/pandatix/go-abnf/cmd/pap@latest
The go.mod file for the module providing named packages contains one or more replace directives. It must not conatin directives that would cause it to be interpreted differently than if it were the main module.
```

In pap go.mod, a `replace` directive is present.

**Comment by pandatix** [comment]
Documentation has been update as of [v0.1.2](https://github.com/pandatix/go-abnf/releases/v0.1.2).

It could be downloaded as a release asset or built manually.

Thanks for pointing this out :smile:
